In [1]:
import numpy as np

### Statistical Methods
- max(maximum element in array)
- min(minimum element in array)
- maximum (maximum element in given multiple arrays)
- minimum (minimum element in given multiple arrays)
- mean (mean value of a array)
- variance
  - summation of (x-x(mean)square)/n
- standard deviation
  - std is square root of variance
- cumsum (sum of elements based on axis= 0 or 1)
- cumprod (product of elements based on axis= 0 or 1) 

In [2]:
a1=np.array([1,2,3,4,5,6])
var=((1-3.5)**2+(2-3.5)**2+(3-3.5)**2+(4-3.5)**2+(5-3.5)**2+(6-3.5)**2)/6
print(var)
print(var**.2)
print(np.mean(a1))
print(np.var(a1))
np.std(a1)

2.9166666666666665
1.2387320081270576
3.5
2.9166666666666665


1.707825127659933

In [3]:
a = np.array([1,2,3])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.var())
print(a.std())

6
1
3
2.0
0.6666666666666666
0.816496580927726


In [4]:
print(a.cumsum())
print(a.cumprod())

[1 3 6]
[1 2 6]


In [5]:
b=np.array([1,3,5,7])
print(b.cumsum())
print(b.cumprod())

[ 1  4  9 16]
[  1   3  15 105]


In [6]:
arr=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(arr.cumprod(axis=0))
print(arr.cumprod(axis=1))

[[  1   2   3]
 [  3   8  15]
 [ 15  48 105]]
[[  1   2   6]
 [  3  12  60]
 [  5  30 210]]


In [7]:
arr=np.random.randint(low=0,high=10,size=20)
print(arr)

[3 0 8 1 6 4 4 0 1 5 1 0 2 0 1 4 8 7 0 8]


In [9]:
arr.reshape((5,4))

array([[3, 0, 8, 1],
       [6, 4, 4, 0],
       [1, 5, 1, 0],
       [2, 0, 1, 4],
       [8, 7, 0, 8]])

In [11]:
arr>=0


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [12]:
print(arr.any())

True


In [13]:
arrr=arr
arrr>0


array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True])

In [14]:
print(arrr.all())

False


In [22]:
arr=np.random.randint(low=0,high=10,size=10)
arr.reshape(2,5)

array([[1, 2, 2, 0, 7],
       [1, 9, 5, 6, 4]])

In [24]:
(arr>5).sum()

4

In [28]:
a='hijrvjgicojjijiji j i jhi jihjijij;ij ih'
print(a.count('j'))
print(len(a))

13
40


In [38]:
a=np.random.randint(low=0,high=100,size=12)
b=(a.reshape((4,3)))
b


array([[49, 40, 41],
       [47, 80, 18],
       [ 0, 73,  9],
       [26, 83, 52]])

In [41]:
b.sort(axis=0)
b

array([[ 0,  9, 49],
       [18, 41, 73],
       [26, 47, 80],
       [40, 52, 83]])

In [42]:
a=np.arange(10)
np.save('first array',a)

In [43]:
np.load('first array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2],[3,4],[5,6],[7,8]])
np.savez('multi',arr1=a,arr2=b)

In [49]:
c=np.load('multi.npz')
c['arr1']

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.savez_compressed('compressed',e=a,d=b)


In [55]:
f=np.load('compressed.npz')
f['e']

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])