- empty_like : return an empty array with shape &type of input.
- ones_like : return an array of ones with shape &type of input.
- zeros_like : return an array of zeros with shape &type of input.
- full_like :  return a new array with shape of input filled with value.
- empty: return a new uninitialized array
- ones : return a new array setting vlues to one.
- zeros: return a new array setting vlues to zero.
- full : return a new array setting filled with value.

In [1]:
import numpy as np

In [9]:
a=np.ones((2,2),dtype=int)
b=np.ones((3,3),dtype=int)
c=np.ones((2,3),dtype=int)
d=np.ones((3,2),dtype=int)
print(a)
print(b)
print(c)
print(d)

[[1 1]
 [1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]]
[[1 1]
 [1 1]
 [1 1]]


In [13]:
a=np.ones_like((1,2))
a

array([1., 1.])

In [18]:
x=np.arange(6)
x=x.reshape((2,3))
print(x)
print(np.empty_like(x))

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


In [31]:
print(np.full((1,30,33),5))

[[[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
  [5 5 5 5 5 5 5 5 5

In [92]:
x=np.arange(56)
x=x.reshape((1,56))
print(x)
print(np.full_like(x,21474836338))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49 50 51 52 53 54 55]]
[[-142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142
  -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142
  -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142
  -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142 -142]]


In [95]:
a=int(input('rows:'))
b=int(input('col:'))
c=np.arange(a*b)
d=c.reshape((a,b))
print(d)
e=int(input('full value:'))
print(np.full_like(d,e))

rows:3
col:3
[[0 1 2]
 [3 4 5]
 [6 7 8]]
full value:3
[[3 3 3]
 [3 3 3]
 [3 3 3]]
0


In [98]:
a=int(input('rows:'))
b=int(input('col:'))
c=np.arange(a*b)
d=c.reshape((a,b))
print(d)
# e=int(input('full value:'))
print(np.empty_like(d))



rows:3
col:3
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [109]:
np.eye((1),dtype=int)

array([[1]])

In [111]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [121]:
print(np.identity(5))
a=np.eye(5,5)
print(a)
print(np.diag(a))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [126]:
a=np.arange(18).reshape(2,3,3)
a.transpose((2,0,1))

array([[[ 0,  3,  6],
        [ 9, 12, 15]],

       [[ 1,  4,  7],
        [10, 13, 16]],

       [[ 2,  5,  8],
        [11, 14, 17]]])

In [138]:
a=np.arange((15))
a
np.sqrt(a)
np.log(a)

C:\Users\APSSDC\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733])

In [140]:
print(np.max(a))
print(np.mean(a))
print(np.min(a))

14
7.0
0


In [148]:
x=np.random.rand((1,8).reshape((2,4))
y=np.array([[1,2,3,4],[1,7,8,9]])
print(x)
print(y)
print(np.maximum(x,y))

SyntaxError: invalid syntax (<ipython-input-148-c97c8f468d25>, line 2)

In [150]:
q=np.arange(9)
q=q+1
remainder=np.modf(q)
remainder

(array([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.]))