## MATRIX
- Matrix Multipliclation
  - multiplication of two matrix
  - dot functionality uses
- Matrix Addition
  - Addition of two matrix with same shape
- Matrix Transpose
  - Changes rows to columns and columns to rows
- Ravel
  - Ravel return reference/view of original array where as
  - If you modify the array you would notice that the value of original array also changes by using.
- Flatten
  - Flatten returns copy of original array
  - If you moidify the array you would  notice that the value of original array not changes.
- Argmin
  - Argmin function return index position of the minimum value in array based on axis(0,1)
- Argmax
  - Argmax function return index position of the maximum value in array based on axis(0,1)
- Vstack
  - Vstack function return vertical array
- Hstack
  - Hstack function return horizontal array 


In [1]:
import numpy as np

In [2]:
a=np.array([[1,7,6],[2,3,4]])
a

array([[1, 7, 6],
       [2, 3, 4]])

In [5]:
b=np.array([[1,7,6],[2,3,4],[2,5,78]])
b

array([[ 1,  7,  6],
       [ 2,  3,  4],
       [ 2,  5, 78]])

In [6]:
a.dot(b)

array([[ 27,  58, 502],
       [ 16,  43, 336]])

In [9]:
arr1=np.array([[1,2,3,4],[4,5,6,7]])
arr2=np.array([[7,6,8,7],[2,4,5,9]])
c=np.concatenate([arr1,arr2],axis=0)
c

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 6, 8, 7],
       [2, 4, 5, 9]])

In [18]:
a=np.array([[1,2,3,4],[4,5,6,7]])
print(a)
b=np.ravel(a)
print(b)

[[1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]


In [19]:
b[-2]=6
print(a)
print(b)

[[1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]


In [25]:
a=np.array([[1,2,3,4],[4,5,6,7]])
print(a)
b=a.flatten()
print(b)

[[1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]


In [28]:
b[-2]=-10
print(a)
print(b)

[[1 2 3 4]
 [4 5 6 7]]
[  1   2   3   4   4   5 -10   7]


In [29]:
k=np.array([1,23,4,2,4,6734,665,6562])
print(k.argmax())
k.argmin()


5


0

In [30]:
l=np.array([[4,5,6],[5674,3456,678],[3456,34,645787]])
print(l)
print('Row wise:',l.argmax(axis=1))
print('coloumn wise:',l.argmax(axis=0))

[[     4      5      6]
 [  5674   3456    678]
 [  3456     34 645787]]
Row wise: [2 0 2]
coloumn wise: [1 1 2]


In [31]:
l=np.array([[4,5,6],[5674,3456,678],[3456,34,645787]])
print(l)
print('Row wise:',l.argmin(axis=1))
print('coloumn wise:',l.argmin(axis=0))

[[     4      5      6]
 [  5674   3456    678]
 [  3456     34 645787]]
Row wise: [0 2 1]
coloumn wise: [0 0 0]


In [33]:
help(np.vstack)

Help on function vstack in module numpy:

vstack(tup)
    Stack arrays in sequence vertically (row wise).
    
    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the first axis.
        1-D arrays must have the same length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays, will be at least 2-D.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    hstack

In [36]:
a=np.array([[1,2,3],[23,44,4]])
b=np.array([[1,2,3],[23,44,4]])
print(np.vstack((a,b)))

[[ 1  2  3]
 [23 44  4]
 [ 1  2  3]
 [23 44  4]]


In [37]:
a=np.array([[1,2,3],[23,44,4]])
b=np.array([[1,2,3],[23,44,4]])
print(np.hstack((a,b)))

[[ 1  2  3  1  2  3]
 [23 44  4 23 44  4]]
