# 2 problem

In [1]:
import pandas as pd


In [32]:
a=pd.array([2, 4, 6, 8, 10])
b=pd.array([1, 3, 5, 7, 9])
c=a+b
d=a-b
e=a*b
f=a/b
print(c,d,e,f)

<PandasArray>
[3, 7, 11, 15, 19]
Length: 5, dtype: int32 <PandasArray>
[1, 1, 1, 1, 1]
Length: 5, dtype: int32 <PandasArray>
[2, 12, 30, 56, 90]
Length: 5, dtype: int32 <PandasArray>
[2.0, 1.3333333333333333, 1.2, 1.1428571428571428, 1.1111111111111112]
Length: 5, dtype: float64


# problem 7

In [3]:
import numpy as np

In [16]:
a=np.arange(start=1,stop=10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# problem 8

In [20]:
a
b=np.ravel(a)
c=a.flatten()
b[-2]=6
c[-2]=4
print(c)
print(a)
print(b)
print(a)

[1 2 3 4 5 6 7 4 9]
[[1 2 3]
 [4 5 6]
 [7 6 9]]
[1 2 3 4 5 6 7 6 9]
[[1 2 3]
 [4 5 6]
 [7 6 9]]


# problem 9

In [26]:
a
print(a.cumsum())
print(a.min())
print(a.max())
print(a.mean())
print(a.cumprod())
print(a.std())

[ 1  3  6 10 15 21 28 34 43]
1
9
4.777777777777778
[     1      2      6     24    120    720   5040  30240 272160]
2.3934065809486684


# problem 10

In [40]:
a=np.array([[1,2,3],[23,44,4]])
b=np.array([[1,2,3],[23,44,4]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 1  2  3]
 [23 44  4]
 [ 1  2  3]
 [23 44  4]]
[[ 1  2  3  1  2  3]
 [23 44  4 23 44  4]]
